package com.curlp.capaPresentacion;

import controlador.Reportes;
import java.awt.Dimension;
import javax.swing.JDesktopPane;

/**
 * 
 * @author Equipo 1
 */
public class Menu extends javax.swing.JFrame {

    public static JDesktopPane menu;

    public Menu() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Facturacion");

        this.setLayout(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMIRegistrarUsuario = new javax.swing.JMenuItem();
        jMIGestionarUsuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMIRegistrarProducto = new javax.swing.JMenuItem();
        jMIGestionarProductos = new javax.swing.JMenuItem();
        jMIActualizarStock = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMIRegistrarCliente = new javax.swing.JMenuItem();
        jMIGestionarClientes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMIRegistrarCategoria = new javax.swing.JMenuItem();
        jMIGestionarCategorias = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMIRegistrarProveedor = new javax.swing.JMenuItem();
        jMIGestionarProveedores = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMINuevaVenta = new javax.swing.JMenuItem();
        jMIGestionarFacturas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem_reportes_clientes = new javax.swing.JMenuItem();
        jMenuItem_reportes_categorias = new javax.swing.JMenuItem();
        jMenuItem_reportes_productos = new javax.swing.JMenuItem();
        jMenuItem_reportes_ventas = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMICiudades = new javax.swing.JMenuItem();
        jMIMarcas = new javax.swing.JMenuItem();
        jMIInteres = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMICerrarSesion = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem15.setText("jMenuItem15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMenu1.setText("Usuario");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(150, 50));
        jMenu1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jMenu1ItemStateChanged(evt);
            }
        });

        jMIRegistrarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMIRegistrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        jMIRegistrarUsuario.setText("Registrar Usuario");
        jMIRegistrarUsuario.setPreferredSize(new java.awt.Dimension(180, 30));
        jMIRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRegistrarUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMIRegistrarUsuario);

        jMIGestionarUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMIGestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMIGestionarUsuarios.setText("Gestionar Usuarios");
        jMIGestionarUsuarios.setPreferredSize(new java.awt.Dimension(180, 30));
        jMIGestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGestionarUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMIGestionarUsuarios);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenu2.setText("Producto");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        jMIRegistrarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMIRegistrarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-producto.png"))); // NOI18N
        jMIRegistrarProducto.setText("Registrar Producto");
        jMIRegistrarProducto.setPreferredSize(new java.awt.Dimension(200, 30));
        jMIRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRegistrarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMIRegistrarProducto);

        jMIGestionarProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMIGestionarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMIGestionarProductos.setText("Gestionar Productos");
        jMIGestionarProductos.setPreferredSize(new java.awt.Dimension(200, 30));
        jMIGestionarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGestionarProductosActionPerformed(evt);
            }
        });
        jMenu2.add(jMIGestionarProductos);

        jMIActualizarStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMIActualizarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        jMIActualizarStock.setText("Actualizar Stock");
        jMIActualizarStock.setPreferredSize(new java.awt.Dimension(200, 30));
        jMIActualizarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIActualizarStockActionPerformed(evt);
            }
        });
        jMenu2.add(jMIActualizarStock);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenu3.setText("Cliente");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(150, 50));

        jMIRegistrarCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMIRegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        jMIRegistrarCliente.setText("Registrar Cliente");
        jMIRegistrarCliente.setPreferredSize(new java.awt.Dimension(180, 30));
        jMIRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRegistrarClienteActionPerformed(evt);
            }
        });
        jMenu3.add(jMIRegistrarCliente);

        jMIGestionarClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMIGestionarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMIGestionarClientes.setText("Gestionar Clientes");
        jMIGestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGestionarClientesActionPerformed(evt);
            }
        });
        jMenu3.add(jMIGestionarClientes);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenu4.setText("Categoria");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 50));

        jMIRegistrarCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMIRegistrarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        jMIRegistrarCategoria.setText("Registrar Categoria");
        jMIRegistrarCategoria.setPreferredSize(new java.awt.Dimension(200, 30));
        jMIRegistrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRegistrarCategoriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMIRegistrarCategoria);

        jMIGestionarCategorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMIGestionarCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMIGestionarCategorias.setText("Gestionar Categorias");
        jMIGestionarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGestionarCategoriasActionPerformed(evt);
            }
        });
        jMenu4.add(jMIGestionarCategorias);

        jMenuBar1.add(jMenu4);

        jMenu7.setText("Proveedores");
        jMenu7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jMIRegistrarProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMIRegistrarProveedor.setText("Registrar Proveedor");
        jMIRegistrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRegistrarProveedorActionPerformed(evt);
            }
        });
        jMenu7.add(jMIRegistrarProveedor);

        jMIGestionarProveedores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMIGestionarProveedores.setText("Gestionar Proveedores");
        jMIGestionarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGestionarProveedoresActionPerformed(evt);
            }
        });
        jMenu7.add(jMIGestionarProveedores);

        jMenuBar1.add(jMenu7);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        jMenu5.setText("Facturar");
        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(150, 50));

        jMINuevaVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMINuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        jMINuevaVenta.setText("Nueva Venta");
        jMINuevaVenta.setPreferredSize(new java.awt.Dimension(200, 30));
        jMINuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMINuevaVentaActionPerformed(evt);
            }
        });
        jMenu5.add(jMINuevaVenta);

        jMIGestionarFacturas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMIGestionarFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMIGestionarFacturas.setText("Gestionar Ventas");
        jMIGestionarFacturas.setPreferredSize(new java.awt.Dimension(200, 30));
        jMIGestionarFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGestionarFacturasActionPerformed(evt);
            }
        });
        jMenu5.add(jMIGestionarFacturas);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes.png"))); // NOI18N
        jMenu6.setText("Reportes");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_reportes_clientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_reportes_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenuItem_reportes_clientes.setText("Reportes Clientes");
        jMenuItem_reportes_clientes.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_reportes_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_reportes_clientesActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_reportes_clientes);

        jMenuItem_reportes_categorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_reportes_categorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenuItem_reportes_categorias.setText("Reportes Categorias");
        jMenuItem_reportes_categorias.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_reportes_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_reportes_categoriasActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_reportes_categorias);

        jMenuItem_reportes_productos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_reportes_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenuItem_reportes_productos.setText("Reportes Productos");
        jMenuItem_reportes_productos.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_reportes_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_reportes_productosActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_reportes_productos);

        jMenuItem_reportes_ventas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_reportes_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenuItem_reportes_ventas.setText("Reportes Ventas");
        jMenuItem_reportes_ventas.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_reportes_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_reportes_ventasActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_reportes_ventas);

        jMenuBar1.add(jMenu6);

        jMenu9.setText("Mantenimiento");
        jMenu9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jMICiudades.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMICiudades.setText("Ciudades");
        jMenu9.add(jMICiudades);

        jMIMarcas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMIMarcas.setText("Marcas");
        jMenu9.add(jMIMarcas);

        jMIInteres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMIInteres.setText("Interes");
        jMenu9.add(jMIInteres);

        jMenuBar1.add(jMenu9);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu8.setText("Cerrar Sesión");
        jMenu8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(200, 50));

        jMICerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMICerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMICerrarSesion.setText("Cerrar Sesión");
        jMICerrarSesion.setPreferredSize(new java.awt.Dimension(150, 30));
        jMICerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICerrarSesionActionPerformed(evt);
            }
        });
        jMenu8.add(jMICerrarSesion);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_reportes_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_reportes_ventasActionPerformed
        Reportes reporte = new Reportes();
        reporte.ReportesVentas();
    }//GEN-LAST:event_jMenuItem_reportes_ventasActionPerformed

    private void jMIRegistrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRegistrarCategoriaActionPerformed
        
    }//GEN-LAST:event_jMIRegistrarCategoriaActionPerformed

    private void jMIGestionarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGestionarCategoriasActionPerformed
       
    }//GEN-LAST:event_jMIGestionarCategoriasActionPerformed

    private void jMIRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRegistrarProductoActionPerformed
        
    }//GEN-LAST:event_jMIRegistrarProductoActionPerformed

    private void jMIGestionarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGestionarProductosActionPerformed
        
    }//GEN-LAST:event_jMIGestionarProductosActionPerformed

    private void jMIRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRegistrarClienteActionPerformed
        
    }//GEN-LAST:event_jMIRegistrarClienteActionPerformed

    private void jMIGestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGestionarClientesActionPerformed
       
    }//GEN-LAST:event_jMIGestionarClientesActionPerformed

    private void jMIActualizarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIActualizarStockActionPerformed
        
    }//GEN-LAST:event_jMIActualizarStockActionPerformed

    private void jMICerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICerrarSesionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMICerrarSesionActionPerformed

    private void jMIRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRegistrarUsuarioActionPerformed
        
    }//GEN-LAST:event_jMIRegistrarUsuarioActionPerformed

    private void jMIGestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGestionarUsuariosActionPerformed
        
    }//GEN-LAST:event_jMIGestionarUsuariosActionPerformed

    private void jMINuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMINuevaVentaActionPerformed
        
    }//GEN-LAST:event_jMINuevaVentaActionPerformed

    private void jMIGestionarFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGestionarFacturasActionPerformed
        
    }//GEN-LAST:event_jMIGestionarFacturasActionPerformed

    private void jMenuItem_reportes_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_reportes_clientesActionPerformed
        Reportes reporte = new Reportes();
        reporte.ReportesClientes();
    }//GEN-LAST:event_jMenuItem_reportes_clientesActionPerformed

    private void jMenuItem_reportes_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_reportes_productosActionPerformed
        Reportes reporte = new Reportes();
        reporte.ReportesProductos();
    }//GEN-LAST:event_jMenuItem_reportes_productosActionPerformed

    private void jMenuItem_reportes_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_reportes_categoriasActionPerformed
        Reportes reporte = new Reportes();
        reporte.ReportesCategorias();
    }//GEN-LAST:event_jMenuItem_reportes_categoriasActionPerformed

    private void jMenu1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jMenu1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ItemStateChanged

    private void jMIRegistrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRegistrarProveedorActionPerformed
        
    }//GEN-LAST:event_jMIRegistrarProveedorActionPerformed

    private void jMIGestionarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGestionarProveedoresActionPerformed
        jPnlProveedor prov = new jPnlProveedor();
        menu.add(prov);
        prov.setVisible(true);
    }//GEN-LAST:event_jMIGestionarProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMIActualizarStock;
    private javax.swing.JMenuItem jMICerrarSesion;
    private javax.swing.JMenuItem jMICiudades;
    private javax.swing.JMenuItem jMIGestionarCategorias;
    private javax.swing.JMenuItem jMIGestionarClientes;
    private javax.swing.JMenuItem jMIGestionarFacturas;
    private javax.swing.JMenuItem jMIGestionarProductos;
    private javax.swing.JMenuItem jMIGestionarProveedores;
    private javax.swing.JMenuItem jMIGestionarUsuarios;
    private javax.swing.JMenuItem jMIInteres;
    private javax.swing.JMenuItem jMIMarcas;
    private javax.swing.JMenuItem jMINuevaVenta;
    private javax.swing.JMenuItem jMIRegistrarCategoria;
    private javax.swing.JMenuItem jMIRegistrarCliente;
    private javax.swing.JMenuItem jMIRegistrarProducto;
    private javax.swing.JMenuItem jMIRegistrarProveedor;
    private javax.swing.JMenuItem jMIRegistrarUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem_reportes_categorias;
    private javax.swing.JMenuItem jMenuItem_reportes_clientes;
    private javax.swing.JMenuItem jMenuItem_reportes_productos;
    private javax.swing.JMenuItem jMenuItem_reportes_ventas;
    // End of variables declaration//GEN-END:variables
}
