/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.curlp.capaPresentacion;

import com.curlp.capaDatos.CDUsuario;
import com.curlp.capaDatos.Conexion;
import com.curlp.capaLogica.CLUsuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
 
/** 
 *
 * @author Usuario
 */
public class JDLRegistro extends javax.swing.JDialog {
    private CDUsuario  cdUsuario;

    public JDLRegistro(java.awt.Frame parent, boolean modal) throws SQLException {
        
        super(parent, modal);
        initComponents();
        cdUsuario = new CDUsuario();
       
        
    }
    
    private void registrarUsuario() throws SQLException {
    String nombre = jTFNombreUsuario.getText().trim();
    String apellido = jTFApellidos.getText().trim();
    String email = jTFEmail.getText().trim();
    String contraseña = new String(jPIContraseña1.getPassword());
    int idRol = jCBTipoUsuario.getSelectedIndex() + 1; // Asumiendo que el combo empieza en índice 0 y rol 1 es válido

    // Validar datos obligatorios
    if (email.isEmpty() || contraseña.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Email y contraseña son obligatorios.");
        return;
    }

    // Crear objeto usuario y asignar datos
    CLUsuario usuario = new CLUsuario();
    

    // Aquí decides qué pones en nombreUsuario, por ejemplo:
    usuario.setNombre(nombre);
    usuario.setApellidos(apellido);
    usuario.setNombreUsuario(email); // si usas email como login
    usuario.setContraseña(contraseña);
    usuario.setEstado(true); // activo por defecto
    usuario.setIdRol(idRol);

    cdUsuario.insertarUsuario(usuario);
    JOptionPane.showMessageDialog(this, "Usuario registrado con éxito.");
    limpiarCampos();
}
    
    private void cargarRoles() {
        List<String> roles = cdUsuario.obtenerRoles();
        jCBTipoUsuario.removeAllItems();
        for (String rol : roles) {
            jCBTipoUsuario.addItem(rol);
        }
}


private void limpiarCampos() {
    jTFNombreUsuario.setText("");
    jTFApellidos.setText("");
    jTFEmail.setText("");
    jPIContraseña1.setText("");
    jCBTipoUsuario.setSelectedIndex(0);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTFApellidos = new javax.swing.JTextField();
        jTFEmail = new javax.swing.JTextField();
        jTFNombreUsuario = new javax.swing.JTextField();
        jPIContraseña1 = new javax.swing.JPasswordField();
        jCBTipoUsuario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jBtnRegistrar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(222, 222, 222));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Usuario"));

        jTFApellidos.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellidos"));

        jTFEmail.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));

        jTFNombreUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        jPIContraseña1.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));

        jCBTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione ", "Administrador", "Cliente ", "Vendedor ", " " }));

        jLabel1.setText("Tipo de Usuario");

        jBtnRegistrar.setText("Registrar");
        jBtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistrarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar ");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPIContraseña1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBtnRegistrar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnCancelar)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPIContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRegistrar)
                    .addComponent(jBtnCancelar))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarActionPerformed
        
       
        try { 
            registrarUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(JDLRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jBtnRegistrarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
         this.dispose();
         
         com.curlp.capaPresentacion.jDlUsuario usuarioDialog = new com.curlp.capaPresentacion.jDlUsuario(null, true);
         usuarioDialog.setVisible(true);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        JDLRegistro dialog = null;
        try {
            dialog = new JDLRegistro(new javax.swing.JFrame(), true);
        } catch (SQLException ex) {
            Logger.getLogger(JDLRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        dialog.setVisible(true);
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnRegistrar;
    private javax.swing.JComboBox<String> jCBTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPIContraseña1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTFApellidos;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
